DROP TABLE IF EXISTS cart_item;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255),
	email VARCHAR(255),
	password VARCHAR(255)
);

CREATE TABLE product (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255),
	category VARCHAR(255),
	price DOUBLE,
	quantity INT
);

CREATE TABLE cart_item (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT,
	product_id BIGINT,
	quantity INT,
	CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(id),
	CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE orders (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT,
	total_amount DOUBLE,
	status VARCHAR(255),
	CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users(id)
);

INSERT INTO users (name, email, password)
VALUES ('Mahendra', 'mahendra@test.com', 'password123');

INSERT INTO users (name, email, password)
VALUES ('Asha', 'asha@test.com', 'secret123');

INSERT INTO product (name, category, price, quantity)
VALUES ('Laptop', 'Electronics', 65000, 10);

INSERT INTO product (name, category, price, quantity)
VALUES ('Phone', 'Electronics', 30000, 15);

INSERT INTO product (name, category, price, quantity)
VALUES ('Shoes', 'Fashion', 2500, 50);

INSERT INTO cart_item (user_id, product_id, quantity)
VALUES (1, 1, 1);

INSERT INTO cart_item (user_id, product_id, quantity)
VALUES (1, 2, 2);

INSERT INTO cart_item (user_id, product_id, quantity)
VALUES (2, 3, 1);

INSERT INTO orders (user_id, total_amount, status)
VALUES (1, 125000, 'CREATED');

INSERT INTO orders (user_id, total_amount, status)
VALUES (2, 2500, 'CREATED');
